
version: 2

# models are files with SELECT statements- 1 SELECT statement per file
models:
  - name: time_frequencies
    description: "A model for Time Frequency data"
    columns:
      - name: track_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: trajectories
    description: "A model for vehicle details and trajectories"
    columns:
      - name: track_id
        description: "The primary key for this table - also the secondary key"
        tests:
          - unique
          - not_null
 
  - name: vehicle_types
    description: "A model for vehicle types"
    columns:
      - name: vehicle_type
        description: "The type of vehicle"
        tests:
          - unique
          - not_null